version: '3'

services:
  app:
    image: node:18.7.0
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - .env
    volumes:
      - ./:/var/www
    command: tail -f /dev/null
    ports:
      - "3000:3000" # websocket
      - "8080:8080" # vue

  database:
    image: mysql:8.0.30
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    env_file:
      - .env
